### ISSUE TITLE
Runtime Warning on main.py

### ISSUE THREAD

**Issue by kresnalita** [povilasb/face-recognition#3]
Hi,
thank you for this tutorial because I can understand the eigenface algorithm :)
but for your project i get this error when I run it.

Do you know why this happen? 
I run this project with anaconda and python 2.7.13 

![error](https://user-images.githubusercontent.com/29522760/27360366-de3e20d4-564a-11e7-9f40-61e62df71c55.JPG)

**Comment by povilasb** [comment]
Unfortunately, this app only runs on python 3.
And there's a big difference between python 2.7 input and python 3 input.
See: https://docs.python.org/2/library/functions.html#input vs https://docs.python.org/3/library/functions.html#input

**Comment by kresnalita** [comment]
Thanks for the reply. I already running with python 3.x. and it's work 👍 :)
And I have some question here. when I use this program about eigenface that you build I can know the value the distance betwen target image and training image. But when I use or face recognition with webcam the result is not good enough because the system doesn't recognize properly. Do yo know how to improve the recognition rate? 

For second question, Is the illuminaton and the variation (like : expression of the face and different brightness level) of the training image very affect the recognition?

Sorry for many question here. Because right now I am learning eigenface for my project in university :)

![capture](https://user-images.githubusercontent.com/29522760/27428550-9b3882fc-576c-11e7-9ff8-a94cd7537f7a.JPG)

**Comment by povilasb** [comment]
Take a look at this discussion https://github.com/povilasb/face-recognition/issues/1

Basically, I think that it's hard to improve accuracy of eigenfaces algorithm.
This algorithm is sensitive to lightning, face position, etc.

Thus I think you should look for more advanced algorithms for better results.
