### ISSUE TITLE
Enquiries

### ISSUE THREAD

**Issue by Sljh0509** [povilasb/face-recognition#63]
Hi, I am glad that you have write the codes using the pca approach. However can i know whether is it possible to add to the function with detecting a unknown faces and show it on the display as "unknown" ?

**Comment by povilasb** [comment]
Technically I think you could: you would need to have a minimal similarity threshold.
For faces that are bellow this threshold, you could say "unknown".
Although, I don't know what the threshold could be :)

**Comment by Sljh0509** [comment]
Noted with thanks. Appreciate it.
